// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdSaeJg_vaivysBb9DmgR2i_v9AJmseuo',
    appId: '1:122791870175:web:e1f0580524ba1d0d5e736a',
    messagingSenderId: '122791870175',
    projectId: 'motimeter-98640',
    authDomain: 'motimeter-98640.firebaseapp.com',
    storageBucket: 'motimeter-98640.appspot.com',
    measurementId: 'G-MHTNRMPZMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHstdZ4lJ7db9i8ATZA_e9sE0z623Cw8',
    appId: '1:122791870175:android:939fafd883c886925e736a',
    messagingSenderId: '122791870175',
    projectId: 'motimeter-98640',
    storageBucket: 'motimeter-98640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC5hf0f-BNeOGhVCSuRwh6QZ8BgDyySjU',
    appId: '1:122791870175:ios:62ef5663b6535fb15e736a',
    messagingSenderId: '122791870175',
    projectId: 'motimeter-98640',
    storageBucket: 'motimeter-98640.appspot.com',
    iosClientId: '122791870175-6hv6rpb0efdg2ddohetevpe9tj5g7j5r.apps.googleusercontent.com',
    iosBundleId: 'ch.bbbaden.motimeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC5hf0f-BNeOGhVCSuRwh6QZ8BgDyySjU',
    appId: '1:122791870175:ios:62ef5663b6535fb15e736a',
    messagingSenderId: '122791870175',
    projectId: 'motimeter-98640',
    storageBucket: 'motimeter-98640.appspot.com',
    iosClientId: '122791870175-6hv6rpb0efdg2ddohetevpe9tj5g7j5r.apps.googleusercontent.com',
    iosBundleId: 'ch.bbbaden.motimeter',
  );
}
